# -*- coding: utf-8 -*-
# temporary here is list of boards

POST_QUOTA = 6
POST_QUOTA_ALL = 20
POST_INERVAL = 100
POST_IMG_INERVAL = 20
POST_IMG_QUOTA = 3

WIPE_INTERVAL_RATIO = 5
WIPE_QUOTA_RATIO = 3
WIPE_STAT_INTERVAL = 120

WATCHER_TIME = 20*60
WATCHERS_MAX = 20

