application: gaeaib
version: release-0-10
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /stats.*                                                                                                                          
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: main.py

admin_console:                                                                                                                           
  pages:                                                                                                                                 
  - name: "Stats"                                                                                                                        
    url: /stats
