application: bankaiapp
version: release-0-19
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

#- url: /
#  static_files: static/index.html
#  upload: static/index.html

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /stats.*                                                                                                                          
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /winry/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py

admin_console:
  pages:
  - name: "Stats"
    url: /stats
    
#error_handlers:
#  - file: static/404.html
