application: bankaiapp
version: release-0-19
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

#- url: /
#  static_files: static/index.html
#  upload: static/index.html

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /_ah/prospective_search
  script: main.py
  login: admin

- url: /winry/.*
  script: main.py
  login: admin

- url: /belki/post/.*
  script: main.py
  login: required


- url: /.*
  script: main.py

admin_console:
  pages:
  - name: "Stats"
    url: /stats

#error_handlers:
#  - file: static/404.html

inbound_services:
- warmup
- channel_presence

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
